### PR TITLE
Remove the background animation on all blocks

### PR DESCRIPTION
**Pull request by palmenhq**
To improve the first contentful paint speed and imo make loading nicer?
For me, running with and without animation locally, lighthouse performance is bumped from 57 to a good 66

So instead of this:

ezgif com-video-to-gif(3)

We do this:
ezgif com-video-to-gif(4)

### CODE REVIEW

**Comment by gustaveen** [comment]
Ah so we get punished for delaying paint. Out of curiosity, would we get better scores if we remove the animation delay? But I'm good with this as a starter since I'm not sure if we want to fade in that part at all. 🙌

**Review by gustaveen — DISMISSED** [review]

**Comment by palmenhq** [comment]
@gustaveen probably we'd improve it but not as much as removing it. IMO it look better without the animation tho 😅  Do you think we should run this through someone else or should i just merge?

**Comment by gustaveen** [comment]
No I think we can merge :) We have been talking about looking over the fade in animations anyway, and I agree that at least the hero can do with out it to get a snappier feel 🙌

**Review by styrelius — DISMISSED** [review]
I agree, it's nicer without the initial white screen 👌

**Comment by styrelius** [comment]
Just one thing I noticed: it feels a bit strange now though that the CTA changes color from black to white?

**Comment by palmenhq** [comment]
@styrelius Nice catch! I've amended the pr

**Review by styrelius — APPROVED** [review]
Nice! 🎨

**Pull request merged**
